### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'detach'

### ISSUE THREAD

**Issue by barl0g** [uqqu/sync_book#1]
### How to reproduce

Default config.py except: use_translation_file = 1

[input_translation.txt](https://github.com/user-attachments/files/18046431/input_translation.txt)
[input_text.txt](https://github.com/user-attachments/files/18046432/input_text.txt)

```
2024-12-07 08:49:27,189 - INFO - self.tokens_src=[But, Arrowhead, ,, if, there, be, pale-faces, in, our, neighborhood, ,, I, confess, I, should, like, to, get, within, hail, of, them, .", The, Tuscarora, now, gave, a, quiet, inclination, of, his, head, ,, and, the, whole, party, descended, from, the, roots, of, the, up-torn, tree, in, silence, ., When, they, reached, the, ground, ,, Arrowhead, intimated, his, intention, to, go, towards, the, fire, ,, and, ascertain, who, had, lighted, it, ;, while, he, advised, his, wife, and, the, two, others, to, return, to, a, canoe, ,, which, they, had, left, in, the, adjacent, stream, ,, and, await, his, return, ., ", Why, ,, chief, ,, this, might, do, on, soundings, ,, and, in, an, offing, where, one, knew, the, channel, ,", returned, old, Cap, ; ", but, in, an, unknown, region, like, this, I, think, it, unsafe, to, trust, the, pilot, alone, too, far, from, the, ship, :, so, ,, with, your, leave, ,, we, will, not, part, company, .", ", What, my, brother, want, ?", asked, the, Indian, gravely, ,, though, without, taking, offence, at, a, distrust, that, was, sufficiently, plain, ., ", Your, company, ,, Master, Arrowhead, ,, and, no, more, ., I, will, go, with, you, and, speak, these, strangers, .", The, Tuscarora, assented, without, difficulty, ,, and, again, he, directed, his, patient, and, submissive, little, wife, ,, who, seldom, turned, her, full, rich, black, eye, on, him, but, to, express, equally, her, respect, ,, her, dread, ,, and, her, love, ,, to, proceed, to, the, boat, ., But, here, Magnet, raised, a, difficulty, ., Although, spirited, ,, and, of, unusual, energy, under, circumstances, of, trial, ,, she, was, but, woman, ;, and, the, idea, of, being, entirely, deserted, by, her, two, male, protectors, ,, in, the, midst, of, a, wilderness, that, her, senses, had, just, told, her, was, seemingly, illimitable, ,, became, so, keenly, painful, ,, that, she, expressed, a, wish, to, accompany, her, uncle, ., ", The, exercise, will, be, a, relief, ,, dear, sir, ,, after, sitting, so, long, in, the, canoe, ,", she, added, ,, as, the, rich, blood, slowly, returned, to, a, cheek, that, had, paled, in, spite, of, her, efforts, to, be, calm, ; ", and, there, may, be, females, with, the, strangers, .", ", Come, ,, then, ,, child, ;, it, is, but, a, cable's, length, ,, and, we, shall, return, an, hour, before, the, sun, sets, .", With, this, permission, ,, the, girl, ,, whose, real, name, was, Mabel, Dunham, ,, prepared, to, be, of, the, party, ;, while, the, Dew-of-June, ,, as, the, wife, of, Arrowhead, was, called, ,, passively, went, her, way, towards, the, canoe, ,, too, much, accustomed, to, obedience, ,, solitude, ,, and, the, gloom, of, the, forest, to, feel, apprehension, ., The, three, who, remained, in, the, wind-row, now, picked, their, way, around, its, tangled, maze, ,, and, gained, the, margin, of, the, woods, .], self.tokens_trg=[-, Вигвам, нет, , -, ответил, Разящая, Стрела, с, обычной, невозмутимостью, ., Слишком, много, дерево, , -, Но, должны, же, здесь, быть, индейцы, .]
Traceback (most recent call last):
  File "/home/user/opt/sync_book/src/main.py", line 130, in <module>
    app.process(input_text)
  File "/home/user/opt/sync_book/src/main.py", line 102, in process
    sentence_obj = Sentence(sentence_text, self.container.entity_counter, self.container)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/opt/sync_book/src/core/sentence_processing.py", line 26, in __init__
    self.aligner = TokenAligner(self.tokens_src, self.tokens_trg)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/opt/sync_book/src/core/alignment.py", line 19, in __init__
    self.alignment[i, j] = self._cosine_similarity(src_token._.embedding, trg_token._.embedding)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/opt/sync_book/src/core/alignment.py", line 32, in _cosine_similarity
    x = x.detach().numpy()
        ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'detach'
```

**Comment by uqqu** [comment]
Thanks for notifying me. I've fixed it.

But with your example still there are sentence alignment errors, starting approximately in the second half of the text. I will think about how to improve this method, but for now it is better to use the inner translator or process the text by parts. You can also try with a different literary translation, but that won't guarantee a successful result.
