### ISSUE TITLE
RuntimeError: Intersect error. Bert "gonna", tensor([4, 9]) (spacy: 1, 2)

### ISSUE THREAD

**Issue by barl0g** [uqqu/sync_book#2]
Error with TBBT prepared subtitles as input_text. Default config.

```
2024-12-08 17:20:18,640 - INFO - Result: [("i'm done", 'я закончил'), ('penny', 'пенни')]                                    
2024-12-08 17:20:18,654 - INFO - self.tokens_src=[I'm, gon, na, be, more, realistic], self.tokens_trg=[Я, буду, более, реалис
тичным]                                                                                                                      
Traceback (most recent call last):                                                                                           
  File "/home/user/opt/sync_book/src/main.py", line 130, in <module>                                                         
    app.process(input_text)                                                                                                  
  File "/home/user/opt/sync_book/src/main.py", line 102, in process                                                          
    sentence_obj = Sentence(sentence_text, self.container.entity_counter, self.container)                                    
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                    
  File "/home/user/opt/sync_book/src/core/sentence_processing.py", line 23, in __init__                                      
    container.text_processor.add_tokens_embeddings(self.sentence, self.tokens_src)                                           
  File "/home/user/opt/sync_book/src/core/text_processing.py", line 119, in add_tokens_embeddings                            
    raise RuntimeError(f'Intersect error. Bert "{token}", {offsets[i]} (spacy: {start}, {end})')                             
RuntimeError: Intersect error. Bert "gonna", tensor([4, 9]) (spacy: 1, 2)
```

[input_text.txt](https://github.com/user-attachments/files/18052615/input_text.txt)

**Comment by uqqu** [comment]
Thanks again. Hm, no problem with _wanna_, _lemme_ and similar, but there is with _gonna_ and _gotta_. Fixed.
